<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/auth.php
// Date: 2016-03-12 21:48:08
return array(
    'failed'   => 'These credentials do not match our records.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
);