<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/auth.php
// Date: 2016-07-02 05:23:30
return array(
    'failed'   => 'These credentials do not match our records.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
);