<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/manager.php
// Date: 2016-07-02 05:23:30
return array(
    'title'              => 'Translations Manager',
    'help'               => 'Select your preferred group and locale below and start translating.',
    'locale_placeholder' => 'Enter the locale you wish to edit. (example: en)',
    'button'             => 'Load',
    'google'             => 'Google Translate',
    'delete'             => 'Delete',
);