<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/lt/auth.php
// Date: 2016-03-12 21:48:08
return array(
    'failed'   => 'Šie prisijungimo duomenys nesutampa su mūsų įrašais.',
    'throttle' => 'Per daug bandymų prisijungti. Prašome pabandyti dar kartą po :seconds sekundžių.',
);