<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/lt/auth.php
// Date: 2016-07-02 05:23:30
return array(
    'failed'   => 'Šie prisijungimo duomenys nesutampa su mūsų įrašais.',
    'throttle' => 'Per daug bandymų prisijungti. Prašome pabandyti dar kartą po :seconds sekundžių.',
);