<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/lt/pagination.php
// Date: 2016-07-02 05:23:30
return array(
    'previous' => '&laquo; Ankstesnis',
    'next'     => 'Kitas &raquo;',
);