<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/lt/pagination.php
// Date: 2016-03-12 21:48:08
return array(
    'previous' => '&laquo; Ankstesnis',
    'next'     => 'Kitas &raquo;',
);
