<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/lt/passwords.php
// Date: 2016-07-02 05:23:30
return array(
    'password' => 'Slaptažodis turi būti bent šešių simbolių ir sutapti.',
    'reset'    => 'Jūsų slaptažodis buvo iš naujo atstatytas!',
    'sent'     => 'Mes e-paštu išsiuntėme naujo slaptažodžio nuorodą!',
    'token'    => 'Slaptažodžio raktas yra neteisingas.',
    'user'     => 'Mes negalime surasti vartotojo su tokiu elektroninio pašto adresu.',
);