<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/lt/validation.php
// Date: 2016-03-12 21:48:08
return array(
    'accepted'   => ':attribute turi būti priimtas.',
    'active_url' => ':attribute nėra galiojantis URL.',
    'after'      => ':attribute turi būti vėliau nei :date.',
    'alpha'      => ':attribute gali būti tik raidės.',
    'alpha_dash' => ':attribute gali būti tik raidės, skaičiai ir brūkšniai.',
    'alpha_num'  => ':attribute gali būti tik raidės ir skaičiai.',
    'array'      => ':attribute turi būti masyvas.',
    'before'     => ':attribute turi būti prieš datą :date.',
    'between' => array(
        'array' => ':attribute turi būti tarp :min ir :max.',
    ),
    'confirmed'  => ':attribute patvirtinimas nesutampa.',
    'exists'     => 'Pasirinktas :attribute negalioja.',
    'filled'     => ':attribute Laukas būtinas.',
    'image'      => ':attribute Turi būti paveiksliukas.',
    'in'         => 'Pasirinktas :attribute negalioja.',
    'ip'         => ':attribute Turi būti galiojantis IP adresas.',
    'json'       => ':attribute Turi būti galiojanti JSON eilutė.',
    'max' => array(
        'file' => ':attribute Negali būti didesnis nei :max kilobaitų.',
    ),
    'mimes'      => ':attribute Turi būti tipo failą: :values.',
    'required'   => ':attribute Laukas būtinas.',
    'regex'      => ':attribute Formatas yra neteisingas.',
    'numeric'    => ':attribute Turi būti skaičius.',
    'not_in'     => 'Pasirinktas :attribute negalioja.',
    'min' => array(
        'string' => ':attribute Turi būti bent :min simbolių.',
    ),
    'string'     => ':attribute Turi būti eilutė.',
    'timezone'   => ':attribute Turi būti galiojanti zona.',
    'unique'     => ':attribute Jau buvo paimtas.',
    'url'        => ':attribute Formatas yra neteisingas.',
);